### ISSUE TITLE
Templating System

### ISSUE THREAD

**Issue by MisterBrownRSA** [mostertb/phpsa-2017-profiles#14]
I'll be adding Slim & Twig for the templating

**Comment by mostertb** [comment]
Awesome! Looking forward to it

**Comment by MisterBrownRSA** [comment]
@mostertb it's done. Check my PR.

**Comment by mostertb** [comment]
I cant seem to find your PR. Are you sure you opened it on the right project?

**Comment by MisterBrownRSA** [comment]
@mostertb let us tell no one about what just happened. I've opened the PR on your project :)

**Comment by mostertb** [comment]
Your secret is safe with me ;)

**Comment by MisterBrownRSA** [comment]
I've updated.
