### ISSUE TITLE
/public/

### ISSUE THREAD

**Issue by MisterBrownRSA** [mostertb/phpsa-2017-profiles#22]
Hey man, Thanks for the merge. However, it seems to have crashed the site due to the fact that it's forcing to /public/

I added a .htaccess, and I thought that this would solve it, however I realize now that it's possible that the home_dir in the php.ini could have been modified.

Either remove the .htaccess or change the environment. :)

**Comment by mostertb** [comment]
Hey

I see that. I think I've fixed it in my last couple of commits. Have a look at what I've done and let me know if you're happy

**Comment by MisterBrownRSA** [comment]
Need to add npm install to the readme (for bulma dependency)

**Comment by MisterBrownRSA** [comment]
I just noticed that going to http://www.phpsa2017profiles.co.za/ it'll give you the project tree instead of heading to /public
